# Generated by Django 4.2 on 2024-10-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepost',
            options={'verbose_name_plural': 'Page Post'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Post'},
        ),
    ]
