# Generated by Django 4.2 on 2024-10-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pagepost_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Friend'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Friend Request'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Reply Comment'},
        ),
    ]
